services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postsjn
      POSTGRES_DB: productdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: productdb
      DB_PASSWORD: Postsjn
      DB_PORT: 5432
      JWT_SECRET: SuperStrongSecretKey123!@#

volumes:
  pgdata: